name: Generate Atom Feed

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install requests PyRSS2Gen python-dateutil
          
      - name: Generate feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: python generate_feed.py
        
      - name: Commit and push feed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add feed.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update feed"
          git push
